name: Deploy-Flask-App

on: 
  push:
    branches: 
      - main
      
jobs:
  Install_Docker:
    runs-on: self-hosted
    
    steps:
    
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
      
  Copying_App_Data:
    runs-on: self-hosted
    
    steps:
    
    - run: |
        cd /
        sudo mkdir flask_project
        cd flask_project
        touch 1.txt
        ls -la
