name: Deploy-Flask-App

on: 
  push:
    branches: 
      - main
      
jobs:
#  Install_Docker:
#    runs-on: self-hosted
    
#    steps:
    
#    - name: Install Docker
#     uses: docker-practice/actions-setup-docker@master
      
  Copying_App_Data:
    runs-on: self-hosted
    
    steps:
    
#    - name: Make a volume directory
#      run: 
#        cd /
#        sudo mkdir flask_project
        
    - name: Copying data
      uses: actions/checkout@v1
      
    - name: Move data
      run: mv * /flask_project
