name: Deploy-Flask-App
env: 
  PROD_DIRECTORY : flask_project
  USER_HOME_DIR : /home/ubuntu

on: 
  push:
    branches: 
      - main
      
jobs:
#  Install_Docker:
#    runs-on: self-hosted
    
#    steps:
    
#    - name: Install Docker
#      uses: docker-practice/actions-setup-docker@master
      
  Copying_App_Data:
    runs-on: self-hosted
    
    steps:
    
    - name: Make a volume directory
      run: | 
        cd ${{ USER_HOME_DIR }}
        mkdir ${{ PROD_DIRECTORY }}
        
    - name: Clone data
      uses: actions/checkout@v1
    
    - name: Copying data
      run: cp * ${{ env.USER_HOME_DIR }}/${{ env.PROD_DIRECTORY }}/
