name: Flask application deploy

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: /home/flask_app
  ENV_NAME: flask
  ADMIN_USER: admin
  ADMIN_PASSWORD: pass
  FLASK_PORT: 5000
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Make a project directory
        run: |
          sudo mkdir ${{ env.PROJECT_NAME }}
          sudo cd ${{ env.PROJECT_NAME }}
          sudo ls -la    
          
      - uses: docker-practice/actions-setup-docker@master

      - uses: actions/checkout@v3
      
      - uses: cuchi/jinja2-action@v1.2.0
        with:
          template: flask_env.py
          output_file: ${{ env.PROJECT_NAME }}/flask_env.py
          strict: true
          variables: |
            ${{ env.ADMIN_USER }}
            ${{ env.ADMIN_PASSWORD }}
             
      - run: cat ${{ env.PROJECT_NAME }}/flask_env.py
