name: Deploy-Flask-App

on: 
  push:
    branches: 
      - main
      
jobs:
  Deploy_Flask_App:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Connection test
      run: sudo apt update
      
