name: Flask application deploy

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: /home/flask_app
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: docker-practice/actions-setup-docker@master

      - uses: actions/checkout@v3
                 
      - run: |
          sudo sed -i "s/${{ secrets.ADMIN_USER}}/{{ADMIN_USER}}/g" flask_env.py
          sudo sed -i "s/${{ secrets.ADMIN_PASSWORD}}/{{ADMIN_PASSWORD}}/g" flask_env.py
          sudo sed -i "s/${{ secrets.FLASK_PORT}}/{{FLASK_PORT}}/g" main.py
          sudo docker-compose up -d
          sudo docker ps
