name: Deploy-Flask-App

on: 
  push:
    branches: 
      - main
      
jobs:
  Install_Docker:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
      
    - name: Docker check
      run: Docker --version
