name: Flask application deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: docker-practice/actions-setup-docker@master

      - uses: actions/checkout@v3
      
      - uses: cuchi/jinja2-action@v1.2.0
        with:
          template: flask_env.py
          output_file: flask_env.py_1
          strict: true
          variables: |
            ADMIN_USER=junior
            
      - run: cat flask_env.py_1  
