name: Deploy-Flask-App

on: 
  push:
    branches: 
      - main
      
jobs:
  Deploy_Flask_App:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AWS_SSH_PRIVATEKEY }}
        known_hosts: ${{ secrets.AWS_SSH_HOST }}
        
    - name: Adding Known Host
      run: ssh-keyscan -H ${{ secrets.AWS_SSH_HOST }} >> ~/.ssh/known_hosts   
      
    - name: Clone project
      uses: actions/checkout@v1
      
    - name: Connect test
      run: |
        ssh ${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_SSH_HOST }} && ls -la
      
#    - name: Copying data to the remote server
#      run: 
